"""Python adapters for ArcTN, opt_einsum, cotengra, and quimb.

Example::

    from quimb.tensor import Circuit
    from arctn import ArcTNOptimizer

    circ = Circuit.from_openqasm2_file("foo.qasm")
    amp = circ.amplitude("0" * circ.N, optimize=ArcTNOptimizer())

The optimizer works with quimb tasks such as ``amplitude``, ``sample``,
``local_expectation``, ``compute_marginal``, ``partial_trace``, and
``to_dense`` without task-specific glue code.

Public entry points
-------------------
============================  ==========================================================
``arctn_path``                Finds one contraction path with a Light or Heavy preset.
``ArcTNOptimizer``            Returns paths to opt_einsum and trees to cotengra.
``arctn_tree``                Builds a cotengra ``ContractionTree``, including slices.
``arctn_contract``            Plans, slices when requested, and executes with an
                              explicit native or opt_einsum array backend.
``arctn_plan``                Returns an immutable, serializable execution plan.
``ArcTNExecutionPlan``       Validates, converts, compiles, or executes one plan.
``ArcTNCompiledContraction``  Reuses a fixed network and SSA path.
``arctn_schedule``            Returns the final path, metrics, and slice plan.
``arctn_simplify``            Reports deterministic simplification without planning.
============================  ==========================================================

Interface conventions
---------------------
1. Python maps arbitrary hashable labels to ArcTN's ``u32`` leg identifiers.
2. Public path-only calls return opt_einsum-style recycled linear paths by
   default. Tree and execution helpers use SSA paths internally.
3. cotengra receives one-character symbols generated by ``oe.get_symbol()``.

"""

from __future__ import annotations

import itertools
import math
import operator
import sys
import time

from ._engine import _configure_bundled_engine

_configure_bundled_engine()

# Load only the native extension bundled in the current wheel.
from . import arctn_py as _rs

# Keep the native module available for explicit low-level use without
# advertising it in the high-level package exports.
arctn_py = _rs
__version__ = _rs.__version__

_AUTO_PRESETS = tuple(_rs.AUTO_PRESETS)
_SLICING_MODES = tuple(_rs.SLICING_MODES)
_EXECUTION_DTYPE_BYTES = {
    "float32": 4,
    "float64": 8,
    "complex64": 8,
    "complex128": 16,
}
_OPTIMIZER_CALL_HISTORY_LIMIT = 256


def _validate_auto_preset(value):
    if not isinstance(value, str) or value not in _AUTO_PRESETS:
        raise ValueError(
            "preset 只支持 'light' 或 'heavy'，"
            f"收到 {value!r}"
        )
    return value


def _validate_slicing_mode(value, target_size):
    if not isinstance(value, str) or value not in _SLICING_MODES:
        raise ValueError(
            "slicing_mode 只支持 'fixed' 或 'dynamic'，"
            f"收到 {value!r}"
        )
    if value == "dynamic" and target_size is None:
        raise ValueError(
            "slicing_mode='dynamic' 时必须同时提供 target_size"
        )
    return value


def _validate_max_time(value):
    if value is None:
        return None
    try:
        value = float(value)
    except (TypeError, ValueError) as exc:
        raise TypeError("max_time 必须是有限且大于 0 的秒数") from exc
    if not math.isfinite(value) or value <= 0.0:
        raise ValueError("max_time 必须是有限且大于 0 的秒数")
    return value


def _validate_planner_weights(flops_weight, read_write_weight):
    values = []
    for name, value in (
        ("flops_weight", flops_weight),
        ("read_write_weight", read_write_weight),
    ):
        if isinstance(value, bool):
            raise TypeError(f"{name} 必须是有限非负数，不能是 bool")
        try:
            value = float(value)
        except (TypeError, ValueError) as exc:
            raise TypeError(f"{name} 必须是有限非负数") from exc
        if not math.isfinite(value) or value < 0.0:
            raise ValueError(f"{name} 必须是有限非负数")
        values.append(value)
    if values == [0.0, 0.0]:
        raise ValueError("flops_weight 和 read_write_weight 不能同时为 0")
    return tuple(values)


def _validate_bool(value, name):
    if not isinstance(value, bool):
        raise TypeError(f"{name} 必须是 bool")
    return value


def _count_arg(value, name, minimum):
    """Parse a Python integer without accepting bool as an accidental budget."""
    if isinstance(value, bool):
        raise TypeError(f"{name} 必须是整数，不能是 bool")
    try:
        value = operator.index(value)
    except TypeError as exc:
        raise TypeError(f"{name} 必须是整数，得到 {value!r}") from exc
    if value < minimum:
        relation = "大于 0" if minimum == 1 else "不小于 0"
        raise ValueError(f"{name} 必须{relation}，得到 {value}")
    if value > sys.maxsize:
        raise OverflowError(f"{name}={value} 超出当前平台 usize 范围 {sys.maxsize}")
    return value


def _validate_target_size(value):
    if value is None:
        return None
    return _count_arg(value, "target_size", 1)


def _validate_execution_backend(value):
    if not isinstance(value, str) or not value or value != value.strip():
        raise ValueError(
            "backend 必须是不带首尾空白的非空字符串，"
            f"收到 {value!r}"
        )
    if value == "auto":
        raise ValueError(
            "backend 必须显式指定；使用 'native'、'numpy' 或已安装的 "
            "opt_einsum 后端名，例如 'cupy'、'torch' 或 'jax'"
        )
    return value

try:
    from opt_einsum.paths import PathOptimizer as _Base
except ImportError:  # pragma: no cover - optional ecosystem dependency
    _Base = object


__all__ = [
    "__version__",
    "ArcTNOptimizer",
    "ArcTNExecutionPlan",
    "ArcTNCompiledContraction",
    "PlanValidationError",
    "arctn_path",
    "arctn_plan",
    "arctn_tree",
    "arctn_contract",
    "arctn_schedule",
    "arctn_simplify",
]


def _to_int_labels(inputs, output, size_dict):
    """Map arbitrary hashable leg labels to deterministic dense ``u32`` IDs.

    Every used leg must have one positive integer dimension, and unused
    ``size_dict`` entries are rejected as likely schema errors.
    """
    if not hasattr(size_dict, "items"):
        raise TypeError("size_dict 必须是提供 .items() 的映射（腿标签 → 正整数维度）")

    label_of = {}

    def idx(lab):
        try:
            i = label_of.get(lab)
        except TypeError as exc:
            raise TypeError(f"腿标签必须可 hash，得到 {lab!r}") from exc
        if i is None:
            i = len(label_of)
            if i > 0xFFFF_FFFF:
                raise ValueError("腿标签数量超过 ArcTN 的 u32 编号上限")
            label_of[lab] = i
        return i

    inputs_i = [[idx(l) for l in term] for term in inputs]
    output_i = [idx(l) for l in output]

    missing = [lab for lab in label_of if lab not in size_dict]
    if missing:
        raise ValueError(f"size_dict 缺少已使用腿的维度: {missing!r}")
    unused = [lab for lab in size_dict if lab not in label_of]
    if unused:
        raise ValueError(f"size_dict 含未在 inputs/output 使用的腿: {unused!r}")

    size_i = {}
    for lab, i in label_of.items():
        raw = size_dict[lab]
        if isinstance(raw, bool):
            raise ValueError(f"腿 {lab!r} 的维度必须是正整数，不能是 bool")
        try:
            dim = operator.index(raw)
        except TypeError as exc:
            raise ValueError(f"腿 {lab!r} 的维度必须是正整数，得到 {raw!r}") from exc
        if dim <= 0:
            raise ValueError(f"腿 {lab!r} 的维度必须为正整数，得到 {dim}")
        if dim > sys.maxsize:
            raise ValueError(
                f"腿 {lab!r} 的维度 {dim} 超出当前平台 usize 范围 {sys.maxsize}"
            )
        size_i[i] = dim
    return inputs_i, output_i, size_i, label_of


def _symbols(label_of, inputs, output, size_dict):
    """Map caller labels to one-character symbols accepted by cotengra."""
    import opt_einsum as oe

    sym_of = {lab: oe.get_symbol(i) for lab, i in label_of.items()}
    inputs_s = ["".join(sym_of[l] for l in term) for term in inputs]
    output_s = "".join(sym_of[l] for l in output)
    # Schema validation has already established every dimension.
    size_s = {sym_of[l]: operator.index(size_dict[l]) for l in label_of}
    return sym_of, inputs_s, output_s, size_s


def _ssa_to_linear_path(ssa_path, n_inputs):
    """Validate an SSA path and convert it to opt_einsum's recycled path."""
    try:
        pairs = [tuple(pair) for pair in ssa_path]
    except TypeError as exc:
        raise TypeError("ssa_path 必须是二元整数对序列") from exc
    if len(pairs) != max(n_inputs - 1, 0):
        raise ValueError(
            f"ssa_path 长度 {len(pairs)} 与 {n_inputs} 个输入不匹配；"
            f"完整路径应有 {max(n_inputs - 1, 0)} 步"
        )

    alive = list(range(n_inputs))
    linear = []
    for step, pair in enumerate(pairs):
        if len(pair) != 2:
            raise ValueError(f"ssa_path[{step}] 不是二元对: {pair!r}")
        a = _count_arg(pair[0], f"ssa_path[{step}][0]", 0)
        b = _count_arg(pair[1], f"ssa_path[{step}][1]", 0)
        if a == b:
            raise ValueError(f"ssa_path[{step}] 自收缩: ({a}, {b})")
        try:
            ia = alive.index(a)
            ib = alive.index(b)
        except ValueError as exc:
            raise ValueError(
                f"ssa_path[{step}] 引用了不存活的张量: ({a}, {b})"
            ) from exc
        lo, hi = sorted((ia, ib))
        linear.append((lo, hi))
        del alive[hi]
        del alive[lo]
        alive.append(n_inputs + step)
    return linear


def _compile_external_expression(inputs, output, size_dict, linear_path):
    """Compile one fixed opt_einsum expression from normalized labels."""
    try:
        import opt_einsum as oe
    except ImportError as exc:
        raise ImportError(
            "外部数组后端需要 opt_einsum；请安装 arctn[execution]"
        ) from exc

    inputs_s = [
        "".join(oe.get_symbol(leg) for leg in term)
        for term in inputs
    ]
    output_s = "".join(oe.get_symbol(leg) for leg in output)
    equation = ",".join(inputs_s) + "->" + output_s
    shapes = [tuple(size_dict[leg] for leg in term) for term in inputs]
    if linear_path:
        return oe.contract_expression(equation, *shapes, optimize=linear_path)
    # opt_einsum rejects optimize=[] for a one-input expression. There is no
    # binary path in this case, so omitting the keyword only performs the
    # declared unary reduction or permutation.
    return oe.contract_expression(equation, *shapes)


def _compile_external_sliced_expression(
    inputs, output, size_dict, *, sliced_legs, ssa_path
):
    """Compile one per-slice expression and its input index plans."""
    linear_path = _ssa_to_linear_path(ssa_path, len(inputs))
    positions = {}
    for position, leg in enumerate(sliced_legs):
        if leg in positions:
            raise ValueError(f"切片腿 {leg} 重复出现")
        if leg not in size_dict:
            raise ValueError(f"切片腿 {leg} 不在 size_dict 中")
        if leg in output:
            raise ValueError(f"切片腿 {leg} 在 output 中")
        occurrences = [term.count(leg) for term in inputs]
        if not any(occurrences):
            raise ValueError(f"切片腿 {leg} 未被任何输入张量持有")
        if any(count > 1 for count in occurrences):
            raise ValueError(f"切片腿 {leg} 在同一输入张量中重复出现，暂不支持")
        positions[leg] = position

    reduced_inputs = tuple(
        tuple(leg for leg in term if leg not in positions)
        for term in inputs
    )
    reduced_sizes = {
        leg: dimension
        for leg, dimension in size_dict.items()
        if leg not in positions
    }
    expression = _compile_external_expression(
        reduced_inputs, output, reduced_sizes, linear_path
    )

    index_plans = []
    for term in inputs:
        plan = tuple(positions.get(leg) for leg in term)
        index_plans.append(plan if any(index is not None for index in plan) else None)
    slice_dimensions = tuple(size_dict[leg] for leg in sliced_legs)
    return expression, tuple(index_plans), slice_dimensions


def _execute_external_sliced_expression(
    expression, arrays, index_plans, slice_dimensions, *, backend
):
    """Execute and sum every slice without changing the array backend."""
    result = None
    ranges = (range(dimension) for dimension in slice_dimensions)
    for assignment in itertools.product(*ranges):
        sliced_arrays = []
        for array, plan in zip(arrays, index_plans):
            if plan is None:
                sliced_arrays.append(array)
                continue
            index = tuple(
                slice(None) if position is None else assignment[position]
                for position in plan
            )
            sliced_arrays.append(array[index])
        part = expression(*sliced_arrays, backend=backend)
        result = part if result is None else result + part

    if result is None:  # Dimensions are validated as positive by the public API.
        raise RuntimeError("切片执行没有生成任何切片")
    return result


# Path-only opt_einsum interface.

def arctn_path(inputs, output, size_dict, *, preset="heavy", seed=0,
               use_ssa=False, max_time=None, flops_weight=1.0,
               read_write_weight=64.0):
    """Find one contraction path with a public Auto preset.

    The objective is
    ``flops_weight * FLOPs + read_write_weight * read/write complexity``.
    ``seed`` specifies the random seed for planning.
    ``max_time`` is cooperative; use an external watchdog for a hard limit.
    """
    preset = _validate_auto_preset(preset)
    flops_weight, read_write_weight = _validate_planner_weights(
        flops_weight, read_write_weight
    )
    inputs_i, output_i, size_i, _ = _to_int_labels(inputs, output, size_dict)
    return _rs.optimize_auto(
        inputs_i, output_i, size_i,
        preset=preset, seed=seed, use_ssa=use_ssa, max_time=max_time,
        flops_weight=flops_weight, read_write_weight=read_write_weight,
    )


class ArcTNOptimizer(_Base):
    """Expose ArcTN Auto to opt_einsum, cotengra, and quimb.

    ``max_time`` is a cooperative planning limit. opt_einsum calls
    :meth:`__call__` for a linear path. For contractions routed through
    cotengra, its ``search`` dispatch
    obtains a ``ContractionTree`` and therefore preserves any slice indices
    selected by ``target_size``. ``call_count`` counts successful integration calls;
    ``calls`` retains the most recent 256 ``(input_count, path_step_count)``
    entries.
    """

    def __init__(self, *, preset="heavy", seed=0, max_time=None,
                 flops_weight=1.0, read_write_weight=64.0,
                 target_size=None, slicing_mode="fixed"):
        self.preset = _validate_auto_preset(preset)
        self.seed = int(seed)
        self.max_time = _validate_max_time(max_time)
        self.flops_weight, self.read_write_weight = _validate_planner_weights(
            flops_weight, read_write_weight
        )
        self.target_size = _validate_target_size(target_size)
        self.slicing_mode = _validate_slicing_mode(
            slicing_mode, self.target_size
        )
        # Keep recent integration diagnostics without unbounded growth.
        self.calls = []
        self.call_count = 0

    def _record_call(self, n_inputs, n_steps):
        self.call_count += 1
        self.calls.append((n_inputs, n_steps))
        if len(self.calls) > _OPTIMIZER_CALL_HISTORY_LIMIT:
            del self.calls[:-_OPTIMIZER_CALL_HISTORY_LIMIT]

    def __call__(self, inputs, output, size_dict, memory_limit=None):
        if memory_limit is not None:
            raise NotImplementedError(
                "ArcTNOptimizer 无法兑现 opt_einsum memory_limit：内存受限规划必须同时"
                "返回路径与切片腿，而 PathOptimizer 契约只能返回路径。请改用 "
                "arctn_tree(target_size=...) 或 arctn_contract(target_size=...)。"
            )
        if self.target_size is not None:
            raise NotImplementedError(
                "ArcTNOptimizer 的 target_size 需要返回 ContractionTree 才能保留"
                "切片腿；当前调用方只请求路径。请在 cotengra/quimb 接受 "
                "ContractionTree 的 optimize= 调用中使用该优化器，或直接调用 "
                "arctn_tree() / arctn_contract()。"
            )
        inputs_i, output_i, size_i, _ = _to_int_labels(inputs, output, size_dict)
        path = _rs.optimize_auto(
            inputs_i, output_i, size_i, preset=self.preset, seed=self.seed,
            use_ssa=False, max_time=self.max_time,
            flops_weight=self.flops_weight,
            read_write_weight=self.read_write_weight,
        )
        self._record_call(len(inputs), len(path))
        return [tuple(p) for p in path]

    def search(self, inputs, output, size_dict):
        """Return a cotengra ``ContractionTree`` through ``search`` dispatch."""
        tree = arctn_tree(
            inputs,
            output,
            size_dict,
            preset=self.preset,
            seed=self.seed,
            target_size=self.target_size,
            slicing_mode=self.slicing_mode,
            max_time=self.max_time,
            flops_weight=self.flops_weight,
            read_write_weight=self.read_write_weight,
        )
        self._record_call(len(inputs), max(0, len(inputs) - 1))
        return tree

    def __repr__(self):
        bits = [
            f"preset={self.preset!r}",
            f"seed={self.seed}",
            f"flops_weight={self.flops_weight}",
            f"read_write_weight={self.read_write_weight}",
        ]
        if self.max_time is not None:
            bits.append(f"max_time={self.max_time}")
        if self.target_size is not None:
            bits.append(f"target_size={self.target_size}")
            bits.append(f"slicing_mode={self.slicing_mode!r}")
        return "ArcTNOptimizer(" + ", ".join(bits) + ")"


# cotengra ContractionTree interface with optional slicing.

def arctn_tree(inputs, output, size_dict, *, preset="heavy", seed=0,
               target_size=None, slicing_mode="fixed", max_time=None, flops_weight=1.0,
               read_write_weight=64.0, return_info=False):
    """Build a cotengra ``ContractionTree`` from an ArcTN plan.

    :class:`ArcTNOptimizer` delegates its ``search`` method to this
    function. cotengra/autoray owns execution and its array backends. Use
    :func:`arctn_contract` for ArcTN's native executor or an explicit opt_einsum
    array backend.

    Parameters
    ----------
    target_size : int, optional
        Maximum elements in one intermediate tensor per slice.
    slicing_mode : {"fixed", "dynamic"}
        ``fixed`` is the default and preserves the path selected before slicing.
        ``dynamic`` may change that path and requires ``target_size``.
        Requested slicing runs after path search; a strict end-to-end wall
        limit requires an external watchdog.
    preset : {"light", "heavy"}
        Public Auto preset.
    max_time : float, optional
        Cooperative planning limit in seconds.
    return_info : bool
        Return ``(tree, info)`` with final path metrics, slicing information,
        and label mapping. The target does not constrain process RSS.
    """
    inputs = tuple(tuple(term) for term in inputs)
    output = tuple(output)
    size_dict = dict(size_dict)
    preset = _validate_auto_preset(preset)
    max_time = _validate_max_time(max_time)
    flops_weight, read_write_weight = _validate_planner_weights(
        flops_weight, read_write_weight
    )
    target_size = _validate_target_size(target_size)
    slicing_mode = _validate_slicing_mode(slicing_mode, target_size)
    has_target = target_size is not None
    target_log2 = math.log2(target_size) if has_target else None
    inputs_i, output_i, size_i, label_of = _to_int_labels(inputs, output, size_dict)
    if not has_target:
        info = _rs.optimize_auto_full(
            inputs_i, output_i, size_i, seed=seed, use_ssa=True,
            preset=preset, max_time=max_time, slicing_mode=slicing_mode,
            flops_weight=flops_weight,
            read_write_weight=read_write_weight,
        )
    else:
        info = _rs.optimize_auto_full(
            inputs_i, output_i, size_i, seed=seed, use_ssa=True,
            preset=preset, max_time=max_time, target_size=target_size,
            slicing_mode=slicing_mode,
            flops_weight=flops_weight, read_write_weight=read_write_weight,
        )
        if not info["sliced"]:
            raise ValueError(
                f"target_size 上限（log2={target_log2:.6g}）不可达：ArcTN 未能找到满足"
                "该上限的切片方案。请增大 target_size 或 max_time。"
            )

    tree, sym_of = _contraction_tree_from_info(
        inputs, output, size_dict, label_of, info
    )

    if return_info:
        info = dict(info)
        info["target_size"] = target_size
        info["target_log2_size"] = target_log2
        info["symbol_of"] = sym_of
        sliced_set = set(info.get("sliced_legs") or [])
        info["sliced_inds"] = [
            sym_of[label] for label, leg in label_of.items() if leg in sliced_set
        ]
        return tree, info
    return tree


def _contraction_tree_from_info(inputs, output, size_dict, label_of, info):
    """Build a Cotengra tree from one already-computed ArcTN result."""
    # Import optional ecosystem dependencies only for tree construction.
    try:
        import cotengra as ctg
        import opt_einsum as oe
    except ImportError as exc:
        raise ImportError(
            "arctn_tree() 需要 opt_einsum/cotengra；"
            "请安装 arctn[execution]"
        ) from exc

    sym_of, inputs_s, output_s, size_s = _symbols(
        label_of, inputs, output, size_dict
    )
    tree = ctg.ContractionTree.from_path(
        inputs_s,
        output_s,
        size_s,
        ssa_path=[tuple(pair) for pair in info["path"]],
    )

    sliced_legs = list(info.get("sliced_legs") or [])
    n_legs = len(label_of)
    for leg in sliced_legs:
        if not (0 <= leg < n_legs):
            raise KeyError(f"切片腿号 {leg} 越界（映射表大小 {n_legs}）")
        tree = tree.remove_ind(oe.get_symbol(leg))
    return tree, sym_of


# Reusable and one-shot execution interfaces.

def _execution_dtype_name(dtype):
    """Return the supported scalar name without importing an array backend."""
    name = getattr(dtype, "name", None)
    if not isinstance(name, str):
        name = str(dtype).rsplit(".", 1)[-1]
    if name not in _EXECUTION_DTYPE_BYTES:
        raise ValueError(
            f"dtype {dtype} 不支持；只支持 float32、float64、"
            "complex64 与 complex128"
        )
    return name


def _prepare_contract_arrays(inputs, size_dict, arrays, *, backend):
    """Validate inputs and preserve external-backend arrays on their device."""

    try:
        values = list(arrays)
    except TypeError as exc:
        raise TypeError("arrays 必须是张量数组序列") from exc
    if len(values) != len(inputs):
        raise ValueError(
            f"arrays 长度 {len(values)} 与 inputs 长度 {len(inputs)} 不一致"
        )

    numpy_owned = backend in {"native", "numpy"}
    np = __import__("numpy") if numpy_owned else None
    numpy_dtypes = (
        {
            np.dtype(np.float32),
            np.dtype(np.float64),
            np.dtype(np.complex64),
            np.dtype(np.complex128),
        }
        if numpy_owned
        else None
    )
    views = []
    dtype_name = None
    for index, (value, legs) in enumerate(zip(values, inputs)):
        array = np.asarray(value) if numpy_owned else value
        if not hasattr(array, "shape") or not hasattr(array, "dtype"):
            raise ValueError(
                f"arrays[{index}] 必须提供 shape 和 dtype"
            )
        if numpy_owned and array.dtype not in numpy_dtypes:
            raise ValueError(
                f"arrays[{index}] 的 dtype {array.dtype} 不支持；"
                "只支持本机字节序的 float32、float64、complex64 与 complex128"
            )
        current_dtype_name = _execution_dtype_name(array.dtype)
        if dtype_name is None:
            dtype_name = current_dtype_name
        elif current_dtype_name != dtype_name:
            raise ValueError(
                f"arrays[{index}] 的 dtype {array.dtype} 与首张量 "
                f"{dtype_name} 不一致"
            )
        expected_shape = tuple(size_dict[leg] for leg in legs)
        try:
            actual_shape = tuple(operator.index(dim) for dim in array.shape)
        except (TypeError, ValueError) as exc:
            raise ValueError(
                f"arrays[{index}] 的 shape {array.shape!r} 不是整数维度"
            ) from exc
        if actual_shape != expected_shape:
            raise ValueError(
                f"arrays[{index}] 形状 {actual_shape} 与网络宣言 "
                f"{expected_shape} 不一致"
            )
        views.append(array)

    if not numpy_owned:
        return views

    # Copy only after all dtypes and shapes pass validation. Preserve declared
    # scalar shapes because NumPy otherwise turns rank-zero arrays into (1,).
    return [
        np.array(array, copy=True, order="C")
        if array.ndim == 0
        else np.ascontiguousarray(array)
        for array in views
    ]


class ArcTNCompiledContraction:
    """A reusable exact contraction with an explicit execution backend.

    Use :meth:`compile` once for a fixed network and SSA path, then call
    :meth:`execute` repeatedly with arrays of the same shapes and dtype family.
    ``backend='native'`` uses ArcTN's Rust executor. Any other explicit backend
    name is passed to :func:`opt_einsum.contract_expression`. Device arrays are
    validated by metadata and are not converted through NumPy.

    This object represents an in-memory compiled contraction.  It is not a
    serialized execution plan and must not be used as a cache across builds.
    Sliced execution remains the responsibility of :func:`arctn_contract` or
    :func:`arctn_tree`.
    """

    def __init__(self, *, backend, inputs, output, size_dict, ssa_path,
                 implementation, compile_wall_s):
        self.backend = backend
        self.inputs = tuple(tuple(term) for term in inputs)
        self.output = tuple(output)
        self.size_dict = dict(size_dict)
        self.ssa_path = tuple(tuple(pair) for pair in ssa_path)
        self._implementation = implementation
        self.compile_wall_s = float(compile_wall_s)
        self.last_execute_wall_s = None
        self.last_dispatch_wall_s = None

    @classmethod
    def compile(cls, inputs, output, size_dict, *, ssa_path, backend="native"):
        """Compile one fixed **SSA-form** contraction path."""
        backend = _validate_execution_backend(backend)
        inputs = tuple(tuple(term) for term in inputs)
        output = tuple(output)
        size_dict = dict(size_dict)
        inputs_i, output_i, size_i, _ = _to_int_labels(
            inputs, output, size_dict
        )
        ssa_path = [tuple(pair) for pair in ssa_path]
        linear_path = _ssa_to_linear_path(ssa_path, len(inputs_i))

        started = time.perf_counter()
        if backend == "native":
            implementation = _rs.CompiledContraction.compile(
                inputs_i, output_i, size_i, ssa_path=ssa_path
            )
        else:
            implementation = _compile_external_expression(
                inputs_i, output_i, size_i, linear_path
            )
        compile_wall_s = time.perf_counter() - started
        return cls(
            backend=backend,
            inputs=inputs_i,
            output=output_i,
            size_dict=size_i,
            ssa_path=ssa_path,
            implementation=implementation,
            compile_wall_s=compile_wall_s,
        )

    def execute(self, arrays):
        """Execute the frozen path without running path search again."""
        arrays = _prepare_contract_arrays(
            self.inputs, self.size_dict, arrays, backend=self.backend
        )
        return self._execute_prepared(arrays)

    def _execute_prepared(self, arrays):
        started = time.perf_counter()
        if self.backend == "native":
            result = self._implementation.execute(arrays)
        else:
            result = self._implementation(*arrays, backend=self.backend)
        dispatch_wall_s = time.perf_counter() - started
        self.last_dispatch_wall_s = dispatch_wall_s
        self.last_execute_wall_s = (
            dispatch_wall_s if self.backend in {"native", "numpy"} else None
        )
        return result

    __call__ = execute

    def stats(self):
        """Return compile/execution timing and backend-specific metadata."""
        result = {
            "backend": self.backend,
            "path_format": "ssa-v1",
            "n_inputs": len(self.inputs),
            "n_steps": len(self.ssa_path),
            "compile_wall_s": self.compile_wall_s,
            "last_execute_wall_s": self.last_execute_wall_s,
            "last_dispatch_wall_s": self.last_dispatch_wall_s,
        }
        if self.backend == "native":
            result.update(dict(self._implementation.stats()))
        else:
            result["implementation"] = "opt_einsum.contract_expression"
        return result

    def __repr__(self):
        return (
            "ArcTNCompiledContraction("
            f"backend={self.backend!r}, n_inputs={len(self.inputs)}, "
            f"n_steps={len(self.ssa_path)})"
        )


def _attach_dtype_contraction_memory_estimates(info, dtype):
    """Attach logical ``A + B + C`` byte estimates to an execution report.

    These values deliberately exclude backend workspace, allocator caches,
    inputs kept outside the contraction, and concurrent slice copies.  They
    are therefore comparable planning diagnostics, not RSS/VRAM limits.
    """
    dtype_name = _execution_dtype_name(dtype)
    itemsize = _EXECUTION_DTYPE_BYTES[dtype_name]
    info["dtype"] = dtype_name
    info["dtype_itemsize"] = itemsize
    info["contraction_memory_estimate_metric"] = (
        "logical_two_inputs_plus_output_bytes"
    )

    has_binary_contraction = bool(info.get("path"))

    def attach(log2_elements_key, log2_bytes_key, estimated_bytes_key):
        log2_elements = info.get(log2_elements_key) if has_binary_contraction else None
        if log2_elements is None:
            info[log2_bytes_key] = None
            info[estimated_bytes_key] = None
            return
        log2_bytes = float(log2_elements) + math.log2(itemsize)
        info[log2_bytes_key] = log2_bytes
        try:
            # ``math.exp2`` is only available in newer Python releases, while
            # ArcTN supports Python 3.9+.  Exponentiation keeps that support.
            estimate = 2.0 ** log2_bytes
        except OverflowError:
            estimate = None
        info[estimated_bytes_key] = (
            estimate if estimate is None or math.isfinite(estimate) else None
        )

    attach(
        "log2_max_contraction_size",
        "log2_max_contraction_bytes",
        "estimated_max_contraction_bytes",
    )
    attach(
        "sliced_log2_max_contraction_size",
        "sliced_log2_max_contraction_bytes",
        "sliced_estimated_max_contraction_bytes",
    )


def arctn_contract(inputs, output, size_dict, arrays, *, preset="heavy", seed=0,
                   target_size=None, slicing_mode="fixed", max_time=None, backend="native",
                   flops_weight=1.0, read_write_weight=64.0,
                   return_info=False):
    """Plan, optionally slice, and execute with an explicit backend.

    ``native`` uses ArcTN's executor and Rayon slice parallelism. Every other
    explicit backend name is delegated to opt_einsum. Sliced execution reuses
    one fixed per-slice expression and accumulates its results on that backend.
    External arrays remain owned by their backend.
    The default wheel does not enable matrixmultiply's optional thread pool.

    Parameters
    ----------
    arrays : Sequence[array]
        Arrays must share one supported floating or complex dtype. Native and
        NumPy inputs become C-contiguous NumPy arrays; external-backend arrays
        are checked through ``shape`` and ``dtype`` without a host copy.
    target_size : int, optional
        Maximum elements in one intermediate tensor per slice.
    slicing_mode : {"fixed", "dynamic"}
        ``fixed`` is the default and preserves the path selected before slicing.
        ``dynamic`` may change that path and requires ``target_size``.
        Requested slicing still runs when path search reaches its stopping
        condition. A strict end-to-end wall limit requires an external watchdog.
    preset : {"light", "heavy"}
        Public Auto preset.
    flops_weight, read_write_weight : float
        Complete-path objective weights.
    max_time : float, optional
        Cooperative planning limit in seconds.
    backend : str
        ``native`` or an explicit opt_einsum backend such as ``numpy``,
        ``cupy``, ``torch`` or ``jax``. ArcTN never selects one implicitly.
    return_info : bool
        Return ``(result, info)`` with execution timing and logical
        ``|A| + |B| + |C|`` byte estimates.

    Notes
    -----
    Native sliced execution gives each in-flight slice its own input copy.
    External sliced execution enumerates slice assignments serially and leaves
    tensor allocation to the selected array backend. ``target_size`` constrains
    one intermediate tensor, not aggregate resident memory.
    """
    inputs = tuple(tuple(term) for term in inputs)
    output = tuple(output)
    size_dict = dict(size_dict)
    preset = _validate_auto_preset(preset)
    backend = _validate_execution_backend(backend)
    max_time = _validate_max_time(max_time)
    flops_weight, read_write_weight = _validate_planner_weights(
        flops_weight, read_write_weight
    )
    target_size = _validate_target_size(target_size)
    slicing_mode = _validate_slicing_mode(slicing_mode, target_size)
    has_target = target_size is not None
    target_log2 = math.log2(target_size) if has_target else None
    inputs_i, output_i, size_i, _ = _to_int_labels(
        inputs, output, size_dict
    )
    input_prepare_started = time.perf_counter()
    arrays = _prepare_contract_arrays(inputs_i, size_i, arrays, backend=backend)
    execution_input_prepare_wall_s = time.perf_counter() - input_prepare_started
    contract_dtype = arrays[0].dtype

    info = _rs.optimize_auto_full(
        inputs_i, output_i, size_i, seed=seed, use_ssa=True,
        preset=preset, max_time=max_time, target_size=target_size,
        slicing_mode=slicing_mode,
        flops_weight=flops_weight, read_write_weight=read_write_weight,
    )
    if has_target:
        if not info["sliced"]:
            raise ValueError(
                f"target_size 上限（log2={target_log2:.6g}）不可达：ArcTN 未能找到满足"
                "该上限的切片方案。请增大 target_size 或 max_time。"
            )

    sliced_legs = list(info.get("sliced_legs") or [])
    expression_compile_wall_s = None
    execution_setup_started = time.perf_counter()
    if backend == "native":
        execution_setup_wall_s = 0.0
        execution_started = time.perf_counter()
        result = _rs.contract_sliced(
            inputs_i, output_i, size_i, arrays,
            sliced_legs,
            ssa_path=[tuple(p) for p in info["path"]],
        )
        execution_dispatch_wall_s = time.perf_counter() - execution_started
        execution_implementation = "arctn.contract_sliced"
    elif sliced_legs:
        expression_compile_started = time.perf_counter()
        expression, index_plans, slice_dimensions = (
            _compile_external_sliced_expression(
                inputs_i,
                output_i,
                size_i,
                sliced_legs=sliced_legs,
                ssa_path=[tuple(pair) for pair in info["path"]],
            )
        )
        expression_compile_wall_s = (
            time.perf_counter() - expression_compile_started
        )
        execution_setup_wall_s = time.perf_counter() - execution_setup_started
        execution_started = time.perf_counter()
        result = _execute_external_sliced_expression(
            expression,
            arrays,
            index_plans,
            slice_dimensions,
            backend=backend,
        )
        execution_dispatch_wall_s = time.perf_counter() - execution_started
        execution_implementation = "arctn.sliced_contract_expression"
    else:
        expression = ArcTNCompiledContraction.compile(
            inputs_i,
            output_i,
            size_i,
            ssa_path=[tuple(pair) for pair in info["path"]],
            backend=backend,
        )
        expression_compile_wall_s = expression.compile_wall_s
        execution_setup_wall_s = time.perf_counter() - execution_setup_started
        result = expression._execute_prepared(arrays)
        execution_dispatch_wall_s = expression.last_dispatch_wall_s
        execution_implementation = "opt_einsum.contract_expression"
    execution_wall_s = (
        execution_setup_wall_s + execution_dispatch_wall_s
        if backend in {"native", "numpy"}
        else None
    )
    execution_total_host_wall_s = (
        execution_input_prepare_wall_s
        + execution_setup_wall_s
        + execution_dispatch_wall_s
    )
    if return_info:
        info = dict(info)
        info["target_size"] = target_size
        info["target_log2_size"] = target_log2
        info["execution_backend"] = backend
        info["execution_implementation"] = execution_implementation
        info["execution_input_prepare_wall_s"] = execution_input_prepare_wall_s
        info["expression_compile_wall_s"] = expression_compile_wall_s
        info["execution_setup_wall_s"] = execution_setup_wall_s
        info["execution_wall_s"] = execution_wall_s
        info["execution_dispatch_wall_s"] = execution_dispatch_wall_s
        info["execution_total_host_wall_s"] = execution_total_host_wall_s
        info["execution_timing_scope"] = (
            "synchronous_host_wall"
            if execution_wall_s is not None
            else "external_backend_completion_not_verified"
        )
        _attach_dtype_contraction_memory_estimates(info, contract_dtype)
        return result, info
    return result


# Final planning result.

def arctn_schedule(inputs, output, size_dict, *, preset="heavy", seed=0,
                   target_size=None, slicing_mode="fixed", max_time=None, use_ssa=False,
                   flops_weight=1.0, read_write_weight=64.0,
                   rate_enabled=True):
    """Run a public Auto preset and return its final planning result.

    Report fields
    -------------
    ``path`` / ``log10_flops`` / ``log2_max_size`` /
    ``log2_max_contraction_size`` / ``log2_total_size`` /
    ``log2_read_write`` / ``log2_peak_size``
        Final path and exact metrics. ``log2_max_contraction_size`` is the
        largest ``|A| + |B| + |C|`` step and does not replace read/write cost.
    ``planner_objective`` / ``flops_weight`` / ``read_write_weight``
        Objective and weights used to score the final path.
    ``sliced`` / ``sliced_legs`` / ``log2_n_slices`` / ``sliced_log10_flops_total`` / ...
        Slice plan. An unreachable ``target_size`` raises ``ValueError``.
    ``slicing_mode``
        ``fixed`` preserves the path selected before slicing. ``dynamic`` may
        change that path and requires ``target_size``. ``fixed`` is the default.
    ``memory_constraint_metric`` / ``memory_target_log2_elements`` /
    ``max_intermediate_log2_elements_per_slice``
        The exact per-slice intermediate constraint, not liveness peak or RSS.

    ``max_time`` is a cooperative limit in seconds. ``rate_enabled`` controls
    whether the preset's rate criterion may stop planning early. Use an external
    watchdog for a hard time limit.
    """
    preset = _validate_auto_preset(preset)
    max_time = _validate_max_time(max_time)
    flops_weight, read_write_weight = _validate_planner_weights(
        flops_weight, read_write_weight
    )
    target_size = _validate_target_size(target_size)
    slicing_mode = _validate_slicing_mode(slicing_mode, target_size)
    rate_enabled = _validate_bool(rate_enabled, "rate_enabled")
    inputs_i, output_i, size_i, _ = _to_int_labels(inputs, output, size_dict)
    report = _rs.optimize_auto_full(
        inputs_i, output_i, size_i, seed=seed, use_ssa=use_ssa,
        preset=preset, max_time=max_time, target_size=target_size,
        slicing_mode=slicing_mode,
        flops_weight=flops_weight, read_write_weight=read_write_weight,
        rate_enabled=rate_enabled,
    )
    report = dict(report)
    report["path_format"] = "ssa-v1" if use_ssa else "linear-v1"
    report["seed"] = int(seed)
    report["max_time"] = max_time
    report["rate_enabled"] = rate_enabled
    report["target_size"] = target_size
    report["target_log2_size"] = (
        math.log2(target_size) if target_size is not None else None
    )
    report["preset"] = preset
    return report


def arctn_simplify(inputs, output, size_dict):
    """Return deterministic network simplification statistics without Auto."""
    inputs_i, output_i, size_i, _ = _to_int_labels(inputs, output, size_dict)
    return _rs.simplify_stats(inputs_i, output_i, size_i)


# Imported after the execution helpers so the plan implementation can reuse the
# same validation, tree conversion, compilation, and backend dispatch paths.
from ._execution_plan import (  # noqa: E402
    ArcTNExecutionPlan,
    PlanValidationError,
    arctn_plan,
)
